### Use variable 1
POST {{$url1}}/post/{{url2}}/aes?{{$url3}}
Authorization: {Basic {{username}} name {{password}}

{
    "my-temp-variable1": "{{ra}}",
    "my-temp-variable2": "{{requestName}}"
}
### Use variable 2
POST {{$url1}}/post/{{url2}}/aes?{{$url3}}
Authorization: {Basic {{username}} name {{password}}

{
    "my-temp-variable1": "{{ra}}",
    "my-temp-variable2": "{{requestName}}"
}